### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'

### ISSUE THREAD

**Issue by kwangbkim** [quantopian/pyfolio#520]
occurs when trying to run an example from the docs

```
stock_rets = pf.utils.get_symbol_rets('FB')
pf.create_returns_tear_sheet(stock_rets, live_start_date='2015-12-1')
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-feb97330a052> in <module>()
----> 1 pf.create_returns_tear_sheet(df, benchmark_rets=benchmark_rets)

~/.pyenv/versions/3.6.0/envs/pyfolio/lib/python3.6/site-packages/pyfolio/plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

~/.pyenv/versions/3.6.0/envs/pyfolio/lib/python3.6/site-packages/pyfolio/tears.py in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, return_fig)
    455                              live_start_date=live_start_date)
    456 
--> 457     plotting.show_worst_drawdown_periods(returns)
    458 
    459     # If the strategy's history is longer than the benchmark's, limit strategy

~/.pyenv/versions/3.6.0/envs/pyfolio/lib/python3.6/site-packages/pyfolio/plotting.py in show_worst_drawdown_periods(returns, top)
   1686     """
   1687 
-> 1688     drawdown_df = timeseries.gen_drawdown_table(returns, top=top)
   1689     utils.print_table(drawdown_df.sort_values('Net drawdown in %',
   1690                                               ascending=False),

~/.pyenv/versions/3.6.0/envs/pyfolio/lib/python3.6/site-packages/pyfolio/timeseries.py in gen_drawdown_table(returns, top)
    995                                                                 recovery,
    996                                                                 freq='B'))
--> 997         df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
    998                                             .strftime('%Y-%m-%d'))
    999         df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
```

**Comment by rkohli3** [comment]
I see the same error. I updated to the latest version of pyfolio and still the error doesn't go away. T

**Comment by brian-from-quantrocket** [comment]
I see this error as well. It was introduced by empyrical 0.4.0. Downgrading empyrical resolves the error:

    pip install empyrical==0.3.4

**Comment by ssanderson** [comment]
I think the issue here is that `ep.cum_returns` isn't preserving the index of its input on the latest empyrical:

On 0.3.4 I see:

```
In [4]: ep.cum_returns(s)
Out[4]:
2017-01-01    0
2017-01-02    0
2017-01-03    0
2017-01-04    0
2017-01-05    0
2017-01-06    0
2017-01-07    0
2017-01-08    0
2017-01-09    0
2017-01-10    0
Freq: D, dtype: int64
```

On 0.4.0 I see:

```
In [13]: ep.cum_returns(s)
Out[13]:
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64
```

**Comment by ssanderson** [comment]
Tentative bugfix PR here: https://github.com/quantopian/empyrical/compare/fix-cum_returns-index?expand=1.

**Comment by ya2366** [comment]
Hi, I tried to downgrade empyrical to 0.3.4 but it didn't solve the error. Is there any new progress on this issue?

**Comment by rkohli3** [comment]
As mentioned by ssanderson, there’s a bug with cum returns. I’d suggest go into the scrip and change the code manually. Worked for me on ep 0.4.0.

Find def cum_returns, change the code as suggested in the link, and reload module.

**Comment by ya2366** [comment]
Thanks

**Comment by jtromans** [comment]
Was this fix already merged? When I load the link it says there is nothing to compare and therefore can't see the fix.

**Comment by richafrank** [comment]
It was merged: https://github.com/quantopian/empyrical/pull/85, but I don't think the fixed empyrical has been released to PyPI yet.

**Comment by jtromans** [comment]
Correct - I just took the code out of the merge although it isn't in the
release as you said.

Kind regards,

James Tromans

**Comment by ssanderson** [comment]
I just released [empyrical 0.4.1](https://pypi.python.org/pypi/empyrical), which has the required bugfix.  If you run into this issue with empyrical >=0.4.1, please let us know here.

**Comment by appusinghi** [comment]
How do I resolve this ?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-9dcd11a12ca4> in <module>
----> 1 pf.create_full_tear_sheet(data)

C:\ProgramData\Anaconda3\lib\site-packages\pyfolio\tears.py in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, style_factor_panel, sectors, caps, shares_held, volumes, percentile, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    209         turnover_denom=turnover_denom,
    210         header_rows=header_rows,
--> 211         set_context=set_context)
    212 
    213     create_interesting_times_tear_sheet(returns,

C:\ProgramData\Anaconda3\lib\site-packages\pyfolio\plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\pyfolio\tears.py in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    502                              header_rows=header_rows)
    503 
--> 504     plotting.show_worst_drawdown_periods(returns)
    505 
    506     vertical_sections = 11

C:\ProgramData\Anaconda3\lib\site-packages\pyfolio\plotting.py in show_worst_drawdown_periods(returns, top)
   1662     """
   1663 
-> 1664     drawdown_df = timeseries.gen_drawdown_table(returns, top=top)
   1665     utils.print_table(
   1666         drawdown_df.sort_values('Net drawdown in %', ascending=False),

C:\ProgramData\Anaconda3\lib\site-packages\pyfolio\timeseries.py in gen_drawdown_table(returns, top)
   1004                                                                 recovery,
   1005                                                                 freq='B'))
-> 1006         df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
   1007                                             .strftime('%Y-%m-%d'))
   1008         df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()

**AttributeError: 'datetime.date' object has no attribute 'to_pydatetime'**

**Comment by stnatter** [comment]
I am having the same problem with `empirical 0.5.3`

**Comment by sokol11** [comment]
I have the same problem. pyfolio 0.9.2, empirical 0.5.3

**Comment by stnatter** [comment]
seems this has been. fixed in https://github.com/quantopian/pyfolio/pull/634

**Comment by sokol11** [comment]
@stnatter Hi Stephen. Your suggestion worked like a charm. I appreciate it.

**Comment by bviorst** [comment]
I am getting this error (empirical 0.5.3) when I run this line of code: 
pf.create_full_tear_sheet(data). Not sure how to fix. Please help, thanks.


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-106-3ddab4691069> in <module>
      1 import numpy as np
----> 2 pf.create_full_tear_sheet(data)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyfolio/tears.py in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, style_factor_panel, sectors, caps, shares_held, volumes, percentile, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    199                                    set_context=set_context,
    200                                    sector_mappings=sector_mappings,
--> 201                                    estimate_intraday=False)
    202 
    203         if transactions is not None:

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyfolio/plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyfolio/tears.py in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    502     if benchmark_rets is not None:
    503         ax_rolling_beta = plt.subplot(gs[i, :], sharex=ax_rolling_returns)
--> 504         i += 1
    505     ax_rolling_volatility = plt.subplot(gs[i, :], sharex=ax_rolling_returns)
    506     i += 1

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyfolio/plotting.py in show_worst_drawdown_periods(returns, top)
   1662     Parameters
   1663     ----------
-> 1664     returns : pd.Series
   1665         Daily returns of the strategy, noncumulative.
   1666          - See full explanation in tears.create_full_tear_sheet.

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyfolio/timeseries.py in gen_drawdown_table(returns, top)
   1006         df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
   1007                                             .strftime('%Y-%m-%d'))
-> 1008         df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()
   1009                                               .strftime('%Y-%m-%d'))
   1010         if isinstance(recovery, float):

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'

**Comment by Ivyzxok** [comment]
I already install the git+, but still not fix this problem

**Comment by Chin-I** [comment]
Same problem.
--
=my error message =
\pyfolio\timeseries.py in gen_drawdown_table(returns, top)
   1006         df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
   1007                                             .strftime('%Y-%m-%d'))
-> 1008         df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()
   1009                                               .strftime('%Y-%m-%d'))
   1010         if isinstance(recovery, float):

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
--
=my conda list=
empyrical                 0.5.3                    pypi_0    pypi
pyfolio                   0.9.2+73.gcfdf82a          pypi_0    pypi

**Comment by nickgeoca** [comment]
Same problem here
```
~/.local/lib/python3.8/site-packages/pyfolio/timeseries.py in gen_drawdown_table(returns, top)
   1006         df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
   1007                                             .strftime('%Y-%m-%d'))
-> 1008         df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()
   1009                                               .strftime('%Y-%m-%d'))
   1010         if isinstance(recovery, float):

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
```
pandas 1.0.5
pyfolio 0.9.2
empyrical 0.5.3

**Comment by VHKA1729** [comment]
To fix the error, if working on Google Colab, use:
```
pip install git+https://github.com/quantopian/pyfolio
```

**Comment by nickgeoca** [comment]
Cool seems to work now. @VHKA1729 , I think I was doing this before. Not sure what changed, but thanks anyway :+1: 
```
pandas 1.0.5
pyfolio 0.9.2+73.gcfdf82a
empyrical 0.5.3
```

**Comment by steelep** [comment]
Hmmm im still getting that error - even running the patch:

```
pandas                     1.0.5 4.4.2           
empyrical                 0.5.3       
pyfolio                     0.9.2+73.gcfdf82a  

```

**Comment by euribate** [comment]
Hi all I getting the same issue, is anybody looking at this? with this error I cannot use pyfolio. 
python 3.6
pandas 1.0.5
numpy 1.18.5
pyfolio 0.9.2
empyrical 0.5.3


I got the foloowing error:

AttributeError                            Traceback (most recent call last)
<ipython-input-20-687ad2ac420b> in <module>
----> 1 pf.create_full_tear_sheet(Globale, benchmark_rets=Bench)

~\Miniconda3\envs\lavoro\lib\site-packages\pyfolio\tears.py in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, style_factor_panel, sectors, caps, shares_held, volumes, percentile, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    209         turnover_denom=turnover_denom,
    210         header_rows=header_rows,
--> 211         set_context=set_context)
    212 
    213     create_interesting_times_tear_sheet(returns,

~\Miniconda3\envs\lavoro\lib\site-packages\pyfolio\plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

~\Miniconda3\envs\lavoro\lib\site-packages\pyfolio\tears.py in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    502                              header_rows=header_rows)
    503 
--> 504     plotting.show_worst_drawdown_periods(returns)
    505 
    506     vertical_sections = 11

~\Miniconda3\envs\lavoro\lib\site-packages\pyfolio\plotting.py in show_worst_drawdown_periods(returns, top)
   1662     """
   1663 
-> 1664     drawdown_df = timeseries.gen_drawdown_table(returns, top=top)
   1665     utils.print_table(
   1666         drawdown_df.sort_values('Net drawdown in %', ascending=False),

~\Miniconda3\envs\lavoro\lib\site-packages\pyfolio\timeseries.py in gen_drawdown_table(returns, top)
   1006         df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
   1007                                             .strftime('%Y-%m-%d'))
-> 1008         df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()
   1009                                               .strftime('%Y-%m-%d'))
   1010         if isinstance(recovery, float):

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'

**Comment by akalingking** [comment]
This seems to work for me 'pip install git+https://github.com/quantopian/pyfolio' as mentioned above.

**Comment by euribate** [comment]
Dear Ariel, I tried but got the same message. While installing "pip install git+https://github.com/quantopian/pyfolio" i got this message:


Collecting git+https://github.com/quantopian/pyfolio
  Cloning https://github.com/quantopian/pyfolio to c:\users\u19040\appdata\local\temp\pip-req-build-8_z5l1d7
Note: you may need to restart the kernel to use updated packages.





  Running command git clone -q https://github.com/quantopian/pyfolio 'C:\Users\u19040\AppData\Local\Temp\pip-req-build-8_z5l1d7'
  ERROR: Error [WinError 2] Impossibile trovare il file specificato while executing command git clone -q https://github.com/quantopian/pyfolio 'C:\Users\u19040\AppData\Local\Temp\pip-req-build-8_z5l1d7'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by euribate** [comment]
> This seems to work for me 'pip install git+https://github.com/quantopian/pyfolio' as mentioned above.



> This seems to work for me 'pip install git+https://github.com/quantopian/pyfolio' as mentioned above.

Dear Ariel, I tried but got the same message. While installing "pip install git+https://github.com/quantopian/pyfolio" i got this message:

Collecting git+https://github.com/quantopian/pyfolio
Cloning https://github.com/quantopian/pyfolio to c:\users\u19040\appdata\local\temp\pip-req-build-8_z5l1d7
Note: you may need to restart the kernel to use updated packages.

Running command git clone -q https://github.com/quantopian/pyfolio 'C:\Users\u19040\AppData\Local\Temp\pip-req-build-8_z5l1d7'
ERROR: Error [WinError 2] Impossibile trovare il file specificato while executing command git clone -q https://github.com/quantopian/pyfolio 'C:\Users\u19040\AppData\Local\Temp\pip-req-build-8_z5l1d7'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by akalingking** [comment]
It says you may not have git and need to install it, also if you're on python3 use pip3

**Comment by euribate** [comment]
> It says you may not have git and need to install it, also if you're on python3 use pip3

I tried not working...Now I am trying to install different version of Python and numpy/pandas. Do you know if with a particolar version pyfolio work? or it is just a waste of time?

**Comment by euribate** [comment]
for the benefit of all, I tried with python 3.7 and the 'pip install git+https://github.com/quantopian/pyfolio'  and it is working

**Comment by filipefeitosa** [comment]
I've already installed 'pip install git+https://github.com/quantopian/pyfolio' and I'm using versions: 

pandas 1.0.5
pyfolio 0.9.2
empyrical 0.5.3

But I'm having problems with charts as you can see in the images bellow. Someone can help me?

![Screen Shot 2020-09-02 at 11 13 51](https://user-images.githubusercontent.com/66032105/91994786-65699f00-ed0d-11ea-9e83-24dba7c0fc33.png)

**Comment by ghost** [comment]
fixed this by changing line 893 in file timeseries.py
valley = underwater.index[np.argmin(underwater)-1]  # end of the period

**Comment by PhanikumarCh** [comment]
Thanks Anoop. Fixed it.

**Comment by Ramoncontabil** [comment]
Fixed:
df_drawdowns.loc[i, 'Peak date'] = (peak.dt.to_pydatetime()
                                            .strftime('%Y-%m-%d'))
        df_drawdowns.loc[i, 'Valley date'] = (valley.dt.to_pydatetime()
                                              .strftime('%Y-%m-%d'))
        if isinstance(recovery, float):
            df_drawdowns.loc[i, 'Recovery date'] = recovery
        else:
            df_drawdowns.loc[i, 'Recovery date'] = (recovery.dt.to_pydatetime()
                                                    .strftime('%Y-%m-%d'))

**Comment by mksamanes** [comment]
Hi @Ramoncontabil How did you fix it? I replace lines 1008 to 1016 with what you wrote but I still have the issue, what versions should I have why is this not working I also replace line 893 and the error says is on line 1008

**Comment by Sergey80** [comment]
same thing. reproducable.
 in oct 10 2021. 
 all latest v.:
 - empyrical==0.5.5
 - pyfolio==0.9.2
 - pandas==1.3.3

**Comment by gstulli** [comment]
Para corrigir o erro, basta alterar a linha nº 893 do código de timeseries.py na def get_max_drawdown_underwater(underwater):
de:
    valley = np.argmin(underwater)  # end of the period
para:
    valley = underwater.index[np.argmin(underwater)]  # end of the period

**Comment by samlopezruiz** [comment]
> same thing. reproducable. in oct 10 2021. all latest v.:
> 
>     * empyrical==0.5.5
> 
>     * pyfolio==0.9.2
> 
>     * pandas==1.3.3

x2, but with pandas==2.1.3

**Comment by mxshen** [comment]
> fixed this by changing line 893 in file timeseries.py valley = underwater.index[np.argmin(underwater)-1] # end of the period

shoule it be: `valley = underwater.index[np.argmin(underwater)]`?

**Comment by mxshen** [comment]
> Para corrigir o erro, basta alterar a linha nº 893 do código de timeseries.py na def get_max_drawdown_underwater(underwater): de: valley = np.argmin(underwater) # end of the period para: valley = underwater.index[np.argmin(underwater)] # end of the period

i think should be this, no need to minus 1
